import wx
import wx.xrc
import wx.grid
import matplotlib
matplotlib.use('WXAgg')
import matplotlib.pyplot as plt
from matplotlib.backends.backend_wxagg import FigureCanvasWxAgg as FigureCanvas
import pandas as pd
import re
import template_frame
import gettext
_ = gettext.gettext

EVEN_ROW_COLOUR = '#CCE6FF'
GRID_LINE_COLOUR = '#ccc'

# Load the CSV file
csv_file = 'Food_Nutrition_Dataset (1).csv'
food_data = pd.read_csv(csv_file)

class FoodDataTable(wx.grid.GridTableBase):
    def __init__(self, data):
        super(FoodDataTable, self).__init__()
        self.data = data
        self.col_labels = data.columns.tolist()

    def GetNumberRows(self):
        return len(self.data)

    def GetNumberCols(self):
        return len(self.col_labels)

    def GetValue(self, row, col):
        return str(self.data.iloc[row, col])

    def GetColLabelValue(self, col):
        return self.col_labels[col]


# Create a subclass of the MainFrame generated by wxFormBuilder
class MyAppFrame(template_frame.MainFrame):
    def __init__(self, parent=None):
        super(MyAppFrame, self).__init__(parent)

        # Bind the event for the "Food Search" button
        self.FoodSearch_button.Bind(wx.EVT_BUTTON, self.on_food_search_click)
        self.NutrientBreakdown_button.Bind(wx.EVT_BUTTON, self.on_nutrient_breakdown_click)

    # Event handler for the Food Search button
    def on_food_search_click(self, event):
        dialog = FoodSearchDialog(self)
        dialog.ShowModal()  # Open the dialog when the button is clicked
        dialog.Destroy()

     # Event handler for the Nutrient Breakdown button

    def on_nutrient_breakdown_click(self, event):
        dialog = NutrientBreakdown_Dialog(self)
        dialog.ShowModal()
        dialog.Destroy()


# Create a subclass of FoodSearch_Dialog generated by wxFormBuilder
class FoodSearchDialog(template_frame.FoodSearch_Dialog):
    def __init__(self, parent):
        super(FoodSearchDialog, self).__init__(parent)

        # Load the CSV data (Food_Nutrition_Dataset (1).csv)
        self.df = pd.read_csv('Food_Nutrition_Dataset (1).csv')

        # Set initial grid table with full data
        self.table = FoodDataTable(self.df)
        self.m_grid3.SetTable(self.table, takeOwnership=True)
        self.m_grid3.AutoSize()

        # Bind the Search button event
        self.Search_button.Bind(wx.EVT_BUTTON, self.on_search_click)

    # Event handler for the Search button
    def on_search_click(self, event):
        search_term = self.m_textCtrl1.GetValue().lower()  # Get search term from the text box
        if search_term:
            # Filter food data based on the search term in the 'Food' column
            filtered_data = self.df[self.df['food'].str.contains(search_term, case=False)]

            # Update the grid with the filtered data
            self.update_grid(filtered_data)

    # Function to update the grid with filtered data
    def update_grid(self, data):
        self.m_grid3.ClearGrid()

        # Create a new table with the filtered data and set it in the grid
        self.table = FoodDataTable(data)
        self.m_grid3.SetTable(self.table, takeOwnership=True)
        self.m_grid3.AutoSize()

        # # Optionally, update any static text to show the number of results found
        # result_count = f"{len(data)} results found"
        # self.SetStatusText(result_count)
class NutrientBreakdown_Dialog(wx.Dialog):

    def __init__(self, parent):
        wx.Dialog.__init__(self, parent, id=wx.ID_ANY, title="Nutrient Breakdown", pos=wx.DefaultPosition,
                           size=wx.Size(600, 300), style=wx.DEFAULT_DIALOG_STYLE)

        self.SetSizeHints(wx.DefaultSize, wx.DefaultSize)

        # Vertical box sizer for main layout
        bSizer6 = wx.BoxSizer(wx.VERTICAL)

        # Vertical sizer for Label and ListBox/Panel layout
        bSizer7 = wx.BoxSizer(wx.VERTICAL)

        # StaticText (Label) for "Select Food"
        self.food_label = wx.StaticText(self, wx.ID_ANY, u"Select Food:", wx.DefaultPosition, wx.DefaultSize, 0)
        self.food_label.Wrap(-1)
        bSizer7.Add(self.food_label, 0, wx.ALL, 5)

        # Horizontal sizer for ListBox and Panel
        bSizer10 = wx.BoxSizer(wx.HORIZONTAL)

        # Load the data from the CSV file using pandas
        self.food_data = pd.read_csv('Food_Nutrition_Dataset (1).csv')  # Ensure the file name matches your actual file

        # Extract food names for the ListBox
        food_choices = self.food_data['food'].tolist()  # Extract the list of food items
        self.m_listBox6 = wx.ListBox(self, wx.ID_ANY, wx.DefaultPosition, wx.DefaultSize, food_choices, 0)
        bSizer10.Add(self.m_listBox6, 0, wx.ALL, 5)

        # Add Panel to display pie chart
        self.m_panel3 = wx.Panel(self, wx.ID_ANY, wx.DefaultPosition, wx.DefaultSize, wx.TAB_TRAVERSAL)
        self.m_panel3.SetBackgroundColour(wx.Colour(255, 255, 255))  # White background for the panel
        bSizer10.Add(self.m_panel3, 1, wx.EXPAND | wx.ALL, 5)

        # Add horizontal sizer to vertical sizer
        bSizer7.Add(bSizer10, 1, wx.EXPAND, 5)

        # Add everything to the main sizer
        bSizer6.Add(bSizer7, 1, wx.EXPAND, 5)

        self.SetSizer(bSizer6)
        self.Layout()

        self.Centre(wx.BOTH)

        # Bind the ListBox selection event to the handler function
        self.m_listBox6.Bind(wx.EVT_LISTBOX, self.on_food_selected)

    def on_food_selected(self, event):
        # Get the selected food from the ListBox
        selected_food = self.m_listBox6.GetStringSelection()

        # Find the row corresponding to the selected food
        food_info = self.food_data[self.food_data['food'] == selected_food].iloc[0]

        # Extract nutrient data for the pie chart
        categories = ['Caloric Value', 'Fat', 'Saturated Fats', 'Protein']
        sizes = [food_info['Caloric Value'], food_info['Fat'], food_info['Saturated Fats'], food_info['Protein']]
        colors = ["gold", "yellowgreen", "lightcoral", "lightskyblue"]

        # Create the figure and axis for the pie chart
        fig, ax = plt.subplots(1, 1, figsize=(4, 4))

        # Plot pie chart
        ax.pie(sizes, labels=categories, colors=colors, autopct="%1.1f%%", shadow=True, explode=(0.1, 0.0, 0.0, 0.0))
        ax.set_title(f"Nutrient Breakdown of {selected_food}")

        # Get the panel size to properly fit the chart
        h, w = self.m_panel3.GetSize()
        fig.set_size_inches(h / fig.get_dpi(), w / fig.get_dpi())

        # Embed the Matplotlib figure in the wxPython Panel
        canvas = FigureCanvas(self.m_panel3, -1, fig)
        canvas.SetSize((h, w))

        # Update the layout and refresh the panel to display the chart
        self.Layout()
        self.m_panel3.Refresh()

# Run the application
if __name__ == "__main__":
    app = wx.App(False)
    frame = MyAppFrame(None)
    frame.Show()
    app.MainLoop()